server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Proxy hacia el microservicio de Ventas (Service de k8s "backend-ventas")
    location /api/ventas/ {
        proxy_pass http://backend-ventas:8080/api/v1/ventas/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy hacia el microservicio de Despachos (Service de k8s "backend-despachos")
    location /api/despachos/ {
        proxy_pass http://backend-despachos:8081/api/v1/despachos/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
